<?php

/**
 * @file
 * SensorML generation.
 *
 * SensorML view mode and template for nodes
 *
 */

require_once dirname(__FILE__) . '/sensorml.field.inc';

/**
 * Implements hook_entity_info_alter().
 */
 /*
function sensorml_entity_info_alter(array &$info) {
  // Add an 'sensorml' view mode to all possible entity types.
  foreach (array_keys($info) as $entity_type) {
    if (!empty($info[$entity_type]['view modes'])) {
      $info[$entity_type]['view modes']['sensorml'] = array(
        'label' => t('SensorML'),
        'custom settings' => FALSE,
      );
    }
  }
} */

/**
 * Implements hook_menu().
 */
 
 // defines the path where the SensorML is defined
function sensorml_menu() {
  $items = array();

  $items['node/%node/sensorml'] = array(
    'page callback' => 'sensorml_output_node',
    'page arguments' => array(1),
    'access callback' => 'node_access',
    'access arguments' => array('view', 1),
    'type' => MENU_CALLBACK,
    'file' => 'sensorml.pages.inc',
  );

  return $items;
}

/**
 * Implements hook_entity_view().
 *
 * When an entity is being rendered with the 'sensorml' view mode, convert the theme
 * and template being used to use our own ISO theme/template.
 *
 * @see sensorml_preprocess_sensorml()
 */
function sensorml_entity_view($entity, $type, $view_mode, $langcode) {
  if ($view_mode == 'sensorml') {
    list(, , $bundle) = entity_extract_ids($type, $entity);
    $entity->content += array(
      '#entity' => $entity,
      '#bundle' => $bundle,
      '#theme' => "sensorml",
    );
  }
}

/**
 * Implements hook_theme().
 */
function sensorml_theme($existing, $type, $theme, $path) {
  $info['sensorml'] = array(
    'render element' => 'elements',
    'template' => 'sensorml',
    'path' => $path . '/templates',
  );

  // Add support for our additional sensorML templates.
  $info += drupal_find_theme_templates($info, '.tpl.php', drupal_get_path('module', 'sensorml') . '/templates');

  $info['sensorml_tag'] = array(
    'render element' => 'element',
  );
  $info['sensorml_tags'] = array(
    'render element' => 'element',
  );

  // A theme wrapper for format_xml_elements().
  $info['sensorml_elements'] = array(
    'variables' => array('sensorml' => array()),
  );

  return $info;
}

function theme_sensorml_elements($variables) {
  return format_xml_elements($variables['sensorml']);
}

function theme_sensorml_tag($variables) {
  $element = &$variables['element'];
  if (isset($element['#value'])) {
    $element['#value'] = check_plain($element['#value']);
  }
  elseif ($children = element_children($element)) {
    $element['#value'] = '';
    foreach ($children as $key) {
      $element[$key] += array('#theme' => 'sensorml_tag');
      $element['#value'] .= drupal_render($element[$key]);
    }
  }
  return theme_html_tag($variables);
}

function theme_sensorml_tags($variables) {
  $output = '';
  $element = &$variables['element'];
  foreach (element_children($element) as $key) {
    $sub_element = array('element' => array());
    $sub_element['element']['#tag'] = $element['#tag'];
    if (isset($element['#attributes'])) {
      $sub_element['element']['#attributes'] = $element['#attributes'];
    }
    $sub_element['element']['#value'] = drupal_render($element[$key]);
    $output .= theme_html_tag($sub_element);
  }
  return $output;
}

/**
 * Implements hook_node_view().
 */
function sensorml_node_view($node, $view_mode, $langcode) {
  if ($view_mode != 'sensorml') {
    return;
  }

  if ($node->type == 'sensor') {
    $methods = array();
    $methods['gmd:LI_Lineage'] = array();
	
    if ($qa_items = field_get_items('node', $node, 'field_quality_assurance')) {
      $qa_instance = field_info_instance('node', 'field_quality_assurance', $node->type);
      $methods['gmd:LI_Lineage']['gmd:statement']['gco:CharacterString']= ' Quality Control: '.strip_tags(_text_sanitize($qa_instance, $langcode, $qa_items[0], 'value'));
    }
    if ($items = field_get_items('node', $node, 'field_methods')) {
      $method_instance = field_info_instance('node', 'field_methods', $node->type);
      $instrumentation_instance = field_info_instance('node', 'field_instrumentation', $node->type);
      $instrumentation_values = field_get_items('node', $node, 'field_instrumentation');
      $method = array();
      $method['gmd:LI_ProcessStep'] = array();
      $method['gmd:LI_ProcessStep']['gmd:description'] = array();
      foreach ($items as $delta => $item) {
        $method['gmd:LI_ProcessStep']['gmd:description']['gco:CharacterString'] = strip_tags(_text_sanitize($method_instance, $langcode, $item, 'value'));
        if (!empty($instrumentation_values[$delta])) {          
          $method['gmd:LI_ProcessStep']['gmd:description']['gco:CharacterString'] .= ' Instrumentation:'. strip_tags(_text_sanitize($instrumentation_instance, $langcode, $instrumentation_values[$delta], 'value'));
        }
        $methods['gmd:LI_Lineage'][] = array('key' => 'gmd:processStep', 'value' => $method);
      }
    }
    if (!empty($methods)) {
      $node->content['methods'] = array(
        '#theme' => 'sensorml_elements',
        '#sensorml' => $methods,
      );
    }
	
    $node->content['keywordSets'] = array();
    foreach (element_children($node->content) as $key) {
      if (isset($node->content[$key]['#field_type'])
          && $node->content[$key]['#field_type'] == 'taxonomy_term_reference'
          && $node->content[$key]['#formatter'] == 'taxonomy_sensorml_keywordset') {
        $node->content['keywordSets'][] = $node->content[$key];
      }
    }
	
  }


}

/**
 * Implements hook_date_format_types().
 */
function sensorml_date_format_types() {
  return array(
    'sensorml_yeardate' => t('SensorML yearDate'),
  );
}

/**
 * Implements hook_date_formats().
 */
function sensorml_date_formats() {
  return array(
    array(
      'type' => 'sensorml_yeardate',
      'format' => 'Y-m-d',
      'locales' => array(),
    ),
  );
}

/**
 * Implements hook_preprocess_HOOK() for sensorml.tpl.php.
 */
function template_preprocess_sensorml(&$variables, $hook) {
  $variables['entity'] = $variables['elements']['#entity'];
  $entity = $variables['entity'];
  $entity_type = $variables['elements']['#entity_type'];
  $bundle = $variables['elements']['#bundle'];

  $label = entity_label($entity_type, $entity);
  $uri = entity_uri($entity_type, $entity);
  $variables['url'] = url($uri['path'], array('absolute' => TRUE) + $uri['options']);
  $variables['label'] = check_plain($label);

  $variables['language'] = check_plain($GLOBALS[LANGUAGE_TYPE_CONTENT]->name);
  //$variables['pubPlace'] = check_plain(variable_get('site_name', 'Drupal'));
  


  $variables['namespaces_array'] = array(
   'xmlns:gmd' => "http://www.isotc211.org/2005/gmd", 
   'xmlns:gco' => "http://www.isotc211.org/2005/gco",
   'xmlns:gfc' => "http://www.isotc211.org/2005/gfc",
   'xmlns:gmx' => "http://www.isotc211.org/2005/gmx",
   'xmlns:gml' => "http://www.opengis.net/gml/3.2",  
   'xmlns:xlink' => "http://www.w3.org/1999/xlink",
   'xmlns:xsi' => "http://www.w3.org/2001/XMLSchema-instance", 
   'xsi:schemaLocation' => "http://www.isotc211.org/2005/gmd http://schemas.opengis.net/iso/19139/20070417/gmd/gmd.xsd",
  );


  /*
  if ($entity_type == 'node' && $variables['elements']['#bundle'] == 'sensor') {
    $variables['pubDate'] = format_date($entity->created, 'sensorml_yeardate');
  }
  
  if ($entity_type == 'node' && $variables['elements']['#bundle'] == 'sensor') {
    $variables['date'] = format_date($entity->field_date, 'sensorml_yeardate');
  } */
  
  

  // Helpful $content variable for templates.
  $variables += array('content' => array());
  foreach (element_children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];

    // Remove the field wrappers and classes so we just get native output.
    if (isset($variables['content'][$key]['#theme']) && $variables['content'][$key]['#theme'] == 'field') {
      unset($variables['content'][$key]['#theme']);
    }
  }

  // Ensure that all the fields for this entity are available, even if empty.
  foreach (field_info_instances($entity_type, $bundle) as $instance) {
	  
    if (!isset($variables['content'][$instance['field_name']])) {
      $variables['content'][$instance['field_name']] = '';
    }
  }

  // Add template suggestions to use, starting with the least preferred, and
  // ending with the one to try first if it exists. The last one should be the
  // most specific.
  $variables['theme_hook_suggestions'][] = 'sensorml';
  $variables['theme_hook_suggestions'][] = "sensorml__{$entity_type}__{$bundle}";
}

/**
 * Implements hook_process_HOOK() for sensorml.tpl.php.
 */
function template_process_sensorml(array &$variables) {
  $variables['namespaces'] = $variables['namespaces_array'] ? drupal_attributes($variables['namespaces_array']) : '';
}


function sensorml_debug($message, array $variables = array()) {
  if (variable_get('sensorml_debugging')) {
    drupal_set_message(format_string('SensorML DEBUG: ' . $message, $variables));
    watchdog('sensorml', $message, $variables, WATCHDOG_DEBUG);
  }
}
